26 seeds
kahikatea-2019/MOA pull request #28
Opened 2019-05-01 23:56 UTC by MurdocAV

Seed data completed, ready for a pull request into dev branch

2019-05-01 23:59 UTC, MurdocAV commented
Seeds #26

2019-05-02 01:38 UTC, bryceknz requested changes
Please see the existing `server/db` folder which already contains a folder for seeds.

2019-05-02 01:57 UTC, MurdocAV commented
Should be consistent with the -- postinstal: "db:seed" -- scripts now

2019-05-02 04:14 UTC, chrislaupama submitted a review, later dismissed
You'll need to make a few changes then we'll be all good to go

2019-05-02 04:14 UTC, chrislaupama commented on server/db/seeds/users.js
> +        {id: 1, name: 'Jane', surname: 'Doe', email: 'janedoe@mail.com', hash: '#', role: 'facilitator'},
You will need to change field names here, the data model has been updated

2019-05-02 04:14 UTC, chrislaupama commented on server/db/seeds/cohorts.js
> +        {id: 1, name: 'Kahikatea', year: 2019, campus: 'Auckland'}
the value for year needs to be a string

2019-05-02 22:13 UTC, MurdocAV commented
This branch is ready to be merged into dev, checked again 10:13am

2019-05-03 02:44 UTC, bryceknz commented on server/db/seeds/cohorts.js
> +      ])
Please add a couple more entries so we can ensure good test coverage.

2019-05-03 02:45 UTC, bryceknz commented on server/db/seeds/exercises.js
> +  return knex('table_name').del()
I think you might've forgotten to pass the new table name to `knex` 😊

2019-05-03 02:45 UTC, bryceknz commented on server/db/seeds/exercises.js
> +      return knex('table_name').insert([
^Same as above.

2019-05-03 02:53 UTC, MurdocAV commented
All fixed, Thanks Bryce

2019-05-03 03:01 UTC, bryceknz commented on server/db/seeds/statuses.js
> +  return knex('table_name').del()
Another `table_name` error.

2019-05-03 03:01 UTC, bryceknz commented on server/db/seeds/students.js
> +      ])
Please add some more students :)

2019-05-03 03:04 UTC, MurdocAV commented on server/db/seeds/exercises.js
> +      return knex('table_name').insert([
Sorry, I don't know how i got soo many errors

2019-05-03 03:19 UTC, bryceknz commented on server/db/seeds/students_assessments.js
> +        {id: 1, student_id: 1, assessment_id: 4, status_id: 1, evidence: 'evidence', date_modified: 'date'}
I've just merged a PR that changes the data type of `data_modified` to a _datetime_. Please update the seed data to reflect this :-)
You may want to use [Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)

2019-05-03 04:31 UTC, bryceknz commented on server/db/seeds/students.js
> +        {id: 1, user_id: 2, cohort_id: 1},
Please make the student ids unique.

2019-05-03 04:31 UTC, bryceknz commented on server/db/seeds/exercises.js
> +        {id: 1, assessment_id: 1, titie: 'taxonomic-routing', link: 'https://github.com/dev-academy-challenges/taxonomic-routing'},
Looks like there's a typo in the column name.

2019-05-03 04:32 UTC, bryceknz commented on server/db/seeds/users.js
> +        { id: 1, name: 'Jane', surname: 'Doe', email: 'janedoe@mail.com', hash: '#', role: 'facilitator' },
The fields should be 'firstName' and 'lastName'.

2019-05-03 04:35 UTC, bryceknz approved these changes

2019-05-03 04:36 UTC, merged