8 get particular route
kahikatea-2019/MOA pull request #47
Opened 2019-05-05 20:58 UTC by paul-renwick

Currently passing all tests and working on localhost:3000.

2019-05-05 22:50 UTC, emilyparkes requested changes

2019-05-05 22:50 UTC, emilyparkes commented on server/server.js
> +server.use('/cohorts/', cohortsRoute)
remove `/` at the end please :)

2019-05-05 22:50 UTC, emilyparkes commented on tests/server/routes/particularCohortRoute.test.js
> +const request = require('supertest')
Change the name of this file to reflect the path and filename of the route you are testing.

2019-05-06 00:46 UTC, emilyparkes submitted a review, later dismissed

2019-05-06 00:47 UTC, emilyparkes approved these changes

2019-05-06 00:47 UTC, merged

2019-05-06 00:49 UTC, paul-renwick commented on server/server.js
> +server.use('/cohorts/', cohortsRoute)
Done